### PR TITLE
Added casts

### PR DESCRIPTION
**Pull request by josch1710**
I added some casts, to prevent the many compiler warning, which are really distracting.

### CODE REVIEW

**Comment by komh** [comment]
Ah, I'm using gcc335. Your warnings seems to occur on gcc4 or later. And I have no plans to move to gcc4 or later. yet.

**Comment by josch1710** [comment]
Yes, that might the case.
But since you have the code here on Github. Anybody can build it with gcc 4.x.
So, I think, it would be a nice addition to have that warnings removed by something as simple as casts, which doesn't even hurt ;-)

**Comment by josch1710** [comment]
I removed the attributes. It's only in one commit, not in the resulting code.

**Comment by komh** [comment]
I've solved in other way. Thanks.

**Pull request closed without merging**
